### PR TITLE
Test JSON against schema

### LINKED ISSUE #225: Exercise schema in CI
It would be nice to test the JSON output against the schema in CI. That way I can make sure the JSON I'm generating actually matches the schema I'm producing. Also it will make sure I haven't broken the schema itself. 

I think I can use [AJV](https://ajv.js.org) for this. I'm not sure if it will be annoying to get a JS tool into my otherwise Haskell CI pipeline.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #225.

### CODE REVIEW

File: src/lib/Rattletrap/Console/Main.hs [hunk 1]
```diff
@@ -153,7 +158,7 @@ schema =
   let contentSchema = Content.schema $ List.schema Frame.schema
   in
     Aeson.object
-      [ Json.pair "$schema" "https://json-schema.org/draft-07/schema"
+      [ Json.pair "$schema" "http://json-schema.org/draft-07/schema"
```
Comment (tfausak) [inline src/lib/Rattletrap/Console/Main.hs:161]: AJV doesn't seem to like the HTTPS URL.

File: .github/workflows/ci.yaml [hunk 2]
```diff
@@ -61,6 +61,11 @@ jobs:
 
       - run: cabal test
 
+      - if: matrix.os == 'ubuntu-20.04'
+        run: npm install ajv-cli
+      - if: matrix.os == 'ubuntu-20.04'
+        run: for f in output/????.json; do echo $f; npx ajv -s output/schema -d $f; done
```
Comment (tfausak) [inline .github/workflows/ci.yaml:67]: I should probably re-write this "script" in Haskell and run it on every operating system. It would be similar to `src/util/copy-executable.hs`.

File: src/lib/Rattletrap/Console/Main.hs (hunk 1 above)
Comment (tfausak) [reply src/lib/Rattletrap/Console/Main.hs:161]: https://github.com/ajv-validator/ajv/issues/1450#issuecomment-781550348

**Comment by tfausak** [comment]
For what it's worth, this check takes about 30 seconds to 1 minute on CI.
